FROM clearmatics/zeth-base:latest AS stage1

# 1. Build phase 1: powers of tau rust binaries
ENV POT_PATH=/home/powersoftau
RUN apk --update --no-cache add \
    # bash \
    # git \
    # gcc \
    musl-dev \
    rust \
    cargo

RUN git clone https://github.com/clearmatics/powersoftau ${POT_PATH}
RUN cd ${POT_PATH} \
    && git submodule update --init --recursive \
    && cargo install --path . \
    && mv /root/.cargo/bin/* /usr/local/bin

# 2. Build phase 2: phase 2 c++ binaries
ENV ZETH_PATH=/home/zeth
COPY . ${ZETH_PATH}

RUN cd ${ZETH_PATH} \
    && git submodule update --init --recursive

RUN cd ${ZETH_PATH} && mkdir build && cd build \
    && cmake .. \
    && make pot-process mpc-client-phase2 \
    && mv ${ZETH_PATH}/build/mpc_tools/pot-process /usr/local/bin \
    && mv ${ZETH_PATH}/build/mpc_tools/mpc_phase2/mpc-client-phase2 /usr/local/bin

##

FROM alpine:3.12
## Move rust and c++ binaries from previous image and put it in the PATH
COPY --from=stage1 /usr/local/bin/ /usr/local/bin
RUN apk --update --no-cache add \
    bash \
    gcc # Install necessary shared libs to run the rust binaries
CMD ["/bin/bash"]
