FROM python:3.8-alpine3.12

RUN apk --update --no-cache add \
    build-base \
    linux-headers \
    curl \
    make \
    perl \
    gcc \
    tar \
    libffi-dev \
    # python2-dev \
    python3-dev \
    py3-virtualenv \
    bash

# Copy necessary files in the docker container
COPY ./client /home/zeth

ENV OPENSSL_VERSION="1.1.1g"
ENV CWD="/home/zeth"

RUN cd /home/zeth \
    # && virtualenv env \
    # && . env/bin/activate \
    && pip install -U setuptools \
    && pip install -U wheel pip \
    && curl -O https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz \
    && tar xvf openssl-${OPENSSL_VERSION}.tar.gz \
    && cd openssl-${OPENSSL_VERSION} \
    && ./config no-shared no-ssl2 no-ssl3 -fPIC --prefix=${CWD}/openssl \
    && make && make install

RUN cd /home/zeth \
    && CFLAGS="-I${CWD}/openssl/include" LDFLAGS="-L${CWD}/openssl/lib" pip wheel --wheel-dir wheels --no-binary :all: cryptography

RUN cd /home/zeth \
    && virtualenv env \
    && source env/bin/activate \
    && pip install --no-index --find-links=wheels cryptography \
    && make setup

WORKDIR /home/zeth

CMD ["/bin/bash"]
