#!/usr/bin/env python3

# Copyright (c) 2015-2020 Clearmatics Technologies Ltd
#
# SPDX-License-Identifier: LGPL-3.0+

from commands.constants import \
    PROVER_SERVER_ENDPOINT_DEFAULT, INSTANCE_FILE_DEFAULT, \
    ZETH_SECRET_ADDRESS_FILE_DEFAULT, WALLET_DIR_DEFAULT, \
    ETH_NETWORK_FILE_DEFAULT, ETH_NETWORK_DEFAULT
from commands.utils import ClientConfig
from commands.zeth_deploy import deploy
from commands.zeth_gen_address import gen_address
from commands.zeth_sync import sync
from commands.zeth_mix import mix
from commands.zeth_ls_notes import ls_notes
from commands.zeth_ls_commits import ls_commits
from commands.zeth_token_approve import token_approve
from click import group, command, option, pass_context, ClickException, Context
from click_default_group import DefaultGroup
from typing import Optional, Any


@command()
@pass_context
def help(ctx: Context) -> None:
    """
    Print help and exit
    """
    # Note, this command is implemented to ensure that an error is raised if no
    # subcommand is specified (which also catches errors in scripts).
    print(ctx.parent.get_help())
    raise ClickException("no command specified")


@group(cls=DefaultGroup, default_if_no_args=True, default="help")
@option(
    "--eth-network",
    default=None,
    help="Ethereum RPC endpoint, network or config file "
    f"(default: '{ETH_NETWORK_FILE_DEFAULT}' if it exists, otherwise "
    f"'{ETH_NETWORK_DEFAULT}')")
@option(
    "--prover-server",
    default=PROVER_SERVER_ENDPOINT_DEFAULT,
    help=f"Prover server endpoint (default={PROVER_SERVER_ENDPOINT_DEFAULT})")
@option(
    "--instance-file",
    default=INSTANCE_FILE_DEFAULT,
    help=f"Instance file (default={INSTANCE_FILE_DEFAULT})")
@option(
    "--address-file",
    default=ZETH_SECRET_ADDRESS_FILE_DEFAULT,
    help=f"Zeth zecret address file (default={ZETH_SECRET_ADDRESS_FILE_DEFAULT})")
@option(
    "--wallet-dir",
    default=WALLET_DIR_DEFAULT,
    help=f"Wallet directory (default={WALLET_DIR_DEFAULT})")
@pass_context
def zeth(
        ctx: Context,
        eth_network: Optional[str],
        prover_server: str,
        instance_file: str,
        address_file: str,
        wallet_dir: str) -> None:
    if ctx.invoked_subcommand == "help":
        ctx.invoke(help)
    ctx.ensure_object(dict)
    ctx.obj = ClientConfig(
        eth_network=eth_network,
        prover_server_endpoint=prover_server,
        instance_file=instance_file,
        address_file=address_file,
        wallet_dir=wallet_dir)


zeth.add_command(deploy)
zeth.add_command(gen_address)
zeth.add_command(sync)
zeth.add_command(mix)
zeth.add_command(ls_notes)
zeth.add_command(ls_commits)
zeth.add_command(token_approve)
zeth.add_command(help)


if __name__ == "__main__":
    zeth()  # pylint: disable=no-value-for-parameter
