#!/usr/bin/env python3

from commands.zeth_deploy import deploy
from commands.zeth_deposit import deposit
from commands.zeth_sync import sync
from commands.zeth_send import send
from commands.zeth_withdraw import withdraw
from commands.zeth_balance import balance
from commands.zeth_notes import notes
from click import group, option, pass_context
from typing import Any, Optional


@group()
@option("--host", help="Ethereum node address host:rpc-port")
@pass_context
def zeth(ctx: Any, host: Optional[str]) -> None:
    ctx.ensure_object(dict)
    ctx.obj["HOST"] = host
    print(f"host is {host}")


zeth.add_command(deploy)
zeth.add_command(deposit)
zeth.add_command(sync)
zeth.add_command(send)
zeth.add_command(withdraw)
zeth.add_command(balance)
zeth.add_command(notes)


if __name__ == "__main__":
    zeth()  # pylint: disable=no-value-for-parameter
