#!/usr/bin/env python3

from coordinator.crypto import \
    import_signing_key, get_verification_key, export_verification_key
from click import command, argument


@command()
@argument("key-file")
def public_key(key_file: str) -> None:
    """
    Load signing key and print verification key to stdout.
    """
    with open(key_file, "rb") as key_f:
        key = import_signing_key(key_f.read())
    print(export_verification_key(get_verification_key(key)))


if __name__ == "__main__":
    public_key()
