#!/usr/bin/env python3

from coordinator.crypto import \
    generate_signing_key, get_verification_key, export_signing_key, \
    export_verification_key
from typing import List


def usage(argv0: str) -> None:
    print(f"""
Usage:
  {argv0} [key_output_file]
""")


def generate_key(argv: List[str]) -> int:
    if 2 != len(argv):
        usage(argv[0])
        return 1

    out_file = argv[1]
    signing_key = generate_signing_key()
    verification_key = get_verification_key(signing_key)

    with open(out_file, "wb") as out_f:
        out_f.write(export_signing_key(signing_key))

    print(export_verification_key(verification_key))
    return 0


if __name__ == "__main__":
    import sys
    exit(generate_key(sys.argv))
