#!/usr/bin/env bash

# Simple script to check source files in the repository and ensure that they is
# a Copyright or DISCLAIMER in the first few lines.

export RESULT=0
function check_copyright_files() {
    count=0
    while read -r file ; do
        if ! (head -n 4 ${file} | grep -q "Copyright\|DISCLAIMER") ; then
            echo "check-copyright: ${file}"
            count=$((${count} + 1))
        fi
    done
    return ${count}
}

if ! (git ls-files '*.py' | check_copyright_files && \
          git ls-files 'client/commands' | check_copyright_files && \
          git ls-files 'mpc/commands' | check_copyright_files && \
          git ls-files '*.hpp' '*.cpp' '*.tcc' | check_copyright_files)
then
    echo "check-copyright: ERROR: the above files have missing copyright notices"
    exit 1
fi
