#!/usr/bin/env bash

platform=`uname`
echo platform=${platform}
echo "running against commit: "`git log --oneline --no-decorate -n 1`

set -x
set -e

function format_check() {
    scripts/format
    git diff --no-ext-diff | head -n 20 > format_errors
    num_lines=`cat format_errors | wc -l`
    if [ "0" != "${num_lines}" ] ; then
        echo CODE FORMATTING ERRORS:
        cat format_errors
        exit 1
    fi
}

function build() {
    dir_name=$1
    build_type=$2

    # Enable warnings-as-errors
    cxx_flags="-Werror"

    if [ "Darwin" == "${platform}" ] ; then
        export PATH="/usr/local/opt/llvm/bin:/usr/local/bin:${PATH}"
        export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
        export LIBRARY_PATH="/usr/local/opt/openssl/lib"
        export LDFLAGS="-L/usr/local/opt/llvm/lib -L-L/usr/local/lib"
        export CPPFLAGS="-I/usr/local/opt/llvm/include -I/usr/local/include"

        cxx_flags="${cxx_flags} -Wno-deprecated-declarations"
    fi

    cmake_flags="-DCMAKE_BUILD_TYPE=${build_type}"

    . setup_env.sh
    mkdir -p build
    cd build
    cmake                                    \
        ${cmake_flags}                       \
        -DCMAKE_CXX_FLAGS="${cxx_flags}"     \
        ..

    make -j 2 VERBOSE=1 all build_tests
    make -j 2 check
}

function build_release() {
    build build-release Release
}

function build_debug() {
    build build-debug Debug
}

if [ "${CI_CHECK_FORMAT}" == "1" ] ; then
    format_check
fi

# The CI_USE_DOCKER variable determines whether we should
# re-execute the script in the docker container with CI_USE_DOCKER=0
if [ "${CI_USE_DOCKER}" == "1" ] ; then
    docker pull clearmatics/zeth-base:latest
    docker build -f Dockerfile-zeth -t zeth-dev .
    docker run -t -p 50051:50051 --name zeth zeth-dev:latest $0 $@
else
    eval $@
fi
