#!/usr/bin/env bash

if [ "" == "$1" ] ; then
    files=`git ls-files '*.cpp' '*.cc' '*.hpp' '*.hh' '*.tcc'`
    for f in $files ; do
        echo "FORMATTING $f"
        clang-format -style=file -i $f
    done
else
    for f in $@ ; do
        echo "FORMATTING $f"
        clang-format -style=file -i $f
    done
fi
