#!/usr/bin/env bash

# This script is only intended to run on the CI machines. Not for local
# development.

# Expect 2 arguments.
if [ "$1" == "" ] || [ "$2" == "" ] ; then
   echo "error: invalid arguments"
   echo "Usage: $0 <install-location> <version>"
   echo ""
   echo "If env var INSTALL_ONLY=1, only run sudo make install"
   exit 1
fi

set -e
set -x

. scripts/build_utils.sh
init_platform

INSTALL_DIR=$1
VERSION=$2

if [ "${INSTALL_ONLY}" != "1" ] ; then
    cpp_build_setup
fi

pushd depends

    if ! [ -d grpc ] ; then
        git clone --depth 1 -b ${VERSION} https://github.com/grpc/grpc
        git -C grpc submodule update --depth 1 --init --recursive
    else
        echo grpc directory already exists. skipping download.
    fi

    pushd grpc

        # Install protobuf
        pushd third_party/protobuf
            if [ "${INSTALL_ONLY}" != "1" ] ; then
                [ -e ./configure ] || ./autogen.sh
                DIST_LANG=cpp ./configure --prefix ${INSTALL_DIR}
                make -j $(($(nproc)+1))
            fi
            sudo make install
        popd # third_party/protobuf

        # Install grpc
        mkdir -p build
        pushd build
            if [ "${INSTALL_ONLY}" != "1" ] ; then
                cmake \
                    -DCMAKE_PREFIX_PATH=${INSTALL_DIR}       \
                    -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}    \
                    -DCMAKE_BUILD_TYPE=Release               \
                    -DgRPC_INSTALL=ON                        \
                    -DgRPC_BUILD_TESTS=OFF                   \
                    -DBUILD_TESTING=OFF                      \
                    -DgRPC_SSL_PROVIDER=package              \
                    -DgRPC_PROTOBUF_PROVIDER=package         \
                    -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF      \
                    -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF        \
                    -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
                    -DgRPC_BUILD_GRPC_PHP_PLUGIN=OFF         \
                    -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF        \
                    ..
                make -j"$(($(nproc)+1))"
            fi
            sudo make install
        popd # build

    popd # grpc

popd # depends
