#!/usr/bin/env bash

platform=`uname`
echo platform=${platform}

set -x

python3 --version
which python3 || echo No python3

set -e
set -x

cd mpc
python3 -m venv env
. env/bin/activate
pip install --upgrade pip --progress-bar off
make setup
