#!/usr/bin/env bash

. scripts/test_mpc_common.sh

# Test an mpc server that has been set up with a test handler, using the
# configuration in /testdata.

set -e
. src/mpc/env/bin/activate
set -x

# fake contribution data
echo FAKE > contrib_data

# 1 - private key
# 2 - public key
# 3 - contrib file
function contribute() {
    contrib_digest=`shasum -a 512 $3 | awk '{print $1}'`
    pub_key=`cat $2`
    sig=`sign_contribution $1 ${contrib_digest}`
    curl \
        --fail \
        --fail-early \
        -H 'X-MPC-Public-Key: '${pub_key} \
        -H 'X-MPC-Signature:'${sig} \
        -F "data=@$3" \
        http://127.0.0.1:5000/contribute

}

# attempt to send data as the 2nd contributor
if (contribute testdata/mpc_key2.bin testdata/mpc_key2.pub contrib_data) ; then
    echo Expected premature contribution to fail
    exit 1
fi

# make 4 contributionsn
contribute ${PRV_KEY_1} ${PUB_KEY_1} contrib_data
contribute ${PRV_KEY_2} ${PUB_KEY_2} contrib_data
contribute ${PRV_KEY_3} ${PUB_KEY_3} contrib_data
contribute ${PRV_KEY_4} ${PUB_KEY_4} contrib_data

# check that the server has registered completion
if ! [ -e ${SERVER_DIR}/final-upload ] ; then
    echo "Expected final file on server"
    exit 1
fi

# further contributions should fail
if (contribute testdata/mpc_key4.bin testdata/mpc_key4.pub contrib_data) ; then
    echo Expected repeated contribution to fail
    exit 1
fi
