#!/usr/bin/env bash

set -e
set -x

TRUFFLE_DIR=`pwd`/zeth-contracts
BASE_DIR=_test_zeth_cli
DEPLOYER_DIR=${BASE_DIR}/deployer
ALICE_DIR=${BASE_DIR}/alice
BOB_DIR=${BASE_DIR}/bob
CHARLIE_DIR=${BASE_DIR}/charlie

function run_truffle() {
    pushd ${TRUFFLE_DIR}
    eval truffle $@
    popd
}

function run_as() {
    pushd $1
    shift
    eval $@
    popd
}

# Setup keys

mkdir -p ${BASE_DIR}
pushd ${BASE_DIR}

    if ! [ -e accounts ] ; then
        (run_truffle exec ../scripts/test_zeth_cli_get_accounts.js) > accounts
    fi

    # 1 - name
    function setup_user() {
        mkdir -p $1
        pushd $1
        ! [ -e eth-address ] && \
            (grep $1 ../accounts | grep -oe '0x.*' > eth-address)
        ! [ -e zeth-key.json ] && \
            (zeth key)
        popd
    }

    setup_user deployer
    setup_user alice
    setup_user bob
    setup_user charlie

    # Deploy
    ! [ -e deployer/zeth-instance.json ] && \
        run_as deployer zeth deploy

    cp deployer/zeth-instance.json alice
    cp deployer/zeth-instance.json bob
    cp deployer/zeth-instance.json charlie

    # Alice deposits 200 and sends 100 to Bob
    pushd alice
    if ! [ -e notes/state_zeth ] ; then
        zeth deposit 200
        zeth sync
    fi
    note_id=`zeth notes | tail -n 1 | grep -oe '^[A-Za-z0-9]\+'`
    ! [ "" == ${note_id} ]

    alice_pk=`cat zeth-key.json.pub`
    bob_pk=`cat ../bob/zeth-key.json.pub`
    zeth send \
         --wait \
         --in ${note_id} \
         --out ${alice_pk},100 \
         --out ${bob_pk},100
    popd

    pushd bob
    zeth sync
    note_id=`zeth notes | tail -n 1 | grep -oe '^[A-Za-z0-9]\+'`
    ! [ "" == ${note_id} ]
    popd

    popd
