#!/usr/bin/env bash

POT_PROCESS=$1
[ "" == "${POT_PROCESS}" ] && POT_PROCESS="build/mpc_tools/pot-process"

POT_DATA="testdata/powersoftau_challenge.4.bin"
POT_DATA_DEGREE=16

set -e
set -x

# Check real data
${POT_PROCESS} --check ${POT_DATA} ${POT_DATA_DEGREE}

# Write dummy data
${POT_PROCESS} --dummy /tmp/test_pot-6.bin 64

# Check consistency of dummy data
${POT_PROCESS} --check /tmp/test_pot-6.bin 64

# Generate encoded Lagrange evaluation from real data
${POT_PROCESS} --out /tmp/lagrange-4.bin ${POT_DATA} ${POT_DATA_DEGREE}

# Generate encoded evaluation of Lagrange polynomials of smaller
# degree, from real data
${POT_PROCESS} \
    --out /tmp/lagrange-3.bin \
    --lagrange-degree $((${POT_DATA_DEGREE} / 2)) \
    ${POT_DATA} ${POT_DATA_DEGREE}

set +x
echo "=================================================================="
echo "==                            PASSED                            =="
echo "=================================================================="
