#!/usr/bin/env bash

. scripts/test_mpc_common.sh

# Launch an mpc server with test config

set -e
set -x

rm -rf ${SERVER_DIR}
mkdir -p ${SERVER_DIR}

# Generate server.config.json
now=`python -c 'import time; print(str(time.time()))'`
sed -e "s/TIME/${now}/g" testdata/mpc_server_config.json > ${SERVER_DIR}/server_config.json

# Run the server
set +x
. src/mpc/env/bin/activate
set -x
cd ${SERVER_DIR}
null_server
