#!/usr/bin/env python3

# Copyright (c) 2015-2020 Clearmatics Technologies Ltd
#
# SPDX-License-Identifier: LGPL-3.0+

from test_commands.gen_eth_address import generate_eth_address
from test_commands.fund_eth_address import fund_eth_address
from test_commands.get_eth_balance import get_eth_balance
from test_commands.deploy_test_token import deploy_test_token
from commands.constants import ETH_NETWORK_DEFAULT
from commands.utils import get_eth_rpc_endpoint
from click import group, command, option, pass_context, ClickException, Context
from click_default_group import DefaultGroup


@command()
@pass_context
def help(ctx: Context) -> None:
    """
    Print help and exit
    """
    # Note, this command is implemented to ensure that an error is raised if no
    # subcommand is specified (which also catches errors in scripts).
    print(ctx.parent.get_help())
    raise ClickException("no command specified")


@group(cls=DefaultGroup, default_if_no_args=True, default="help")
@option(
    "--eth-network",
    default=ETH_NETWORK_DEFAULT,
    help=f"Ethereum network to connect to (default: {ETH_NETWORK_DEFAULT})")
@pass_context
def zeth_debug(ctx: Context, eth_network: str) -> None:
    if ctx.invoked_subcommand == "help":
        ctx.invoke(help)
    ctx.ensure_object(dict)
    ctx.obj = {
        "eth_network": eth_network,
        "eth_rpc_endpoint": get_eth_rpc_endpoint(eth_network),
    }


zeth_debug.add_command(generate_eth_address)
zeth_debug.add_command(fund_eth_address)
zeth_debug.add_command(get_eth_balance)
zeth_debug.add_command(deploy_test_token)
zeth_debug.add_command(help)


if __name__ == "__main__":
    zeth_debug()  # pylint: disable=no-value-for-parameter
