#include <iostream>
#include <cstdio>
#include <string>

#include <grpc/grpc.h>
#include <grpcpp/server.h>
#include <grpcpp/server_builder.h>
#include <grpcpp/server_context.h>
#include <grpcpp/security/server_credentials.h>

// Necessary header to parse the data
#include <libsnark/common/data_structures/merkle_tree.hpp>

// Include zeth headers
#include "libsnark_helpers/libsnark_helpers.hpp"
#include "circuits/computation.hpp"
#include "circuits/sha256/sha256_ethereum.hpp"
#include "circuit-wrapper.hpp"
//#include "zethConfig.h"

#include "util.hpp"

// Include the file generated by gRPC
#include "prover.grpc.pb.h"

using grpc::Server;
using grpc::ServerBuilder;
using grpc::ServerContext;
using grpc::ServerReader;
using grpc::ServerReaderWriter;
using grpc::ServerWriter;
using grpc::Status;
using grpc::StatusCode;

// Use the Prover service defined in the proto file
using proverpkg::Prover;

// Use the messages defined in the proto file
using proverpkg::EmptyMessage;
using proverpkg::PackedDigest;
using proverpkg::ProofInputs;
using proverpkg::ProofPublicInputs;
using proverpkg::HexadecimalPointBaseGroup1Affine;
using proverpkg::HexadecimalPointBaseGroup2Affine;
using proverpkg::ExtendedProof;

typedef libff::default_ec_pp ppT;
typedef libff::Fr<ppT> FieldT;
typedef sha256_ethereum<FieldT> HashT;

// Note, these denote the number of INs and OUTs of the JS
// For now this is handled by global consts, but we can easily
// think about fancier things, where the server has some config attributes
// that could be changed via a call to a rcp function like:
// `rpc ConfigProver(ConfigMsg) returns (RespMsg) {}`
// This function could change the config of the server that could thee re-run a
// setup for the new config to gen proofs for the new circuit
//
// We could go even futher and keep the setups of the diff config in a folder
// (a sort of a setup cache)
// to prevent the server from running setups for configs it has already seen
//
// No matter whether this would be a good feature or not, this is out of scope
// for this PoC
const size_t JSIns = 1;
const size_t JSOut = 1;

class ProverImpl final : public Prover::Service {
  Status RunSetup(
    ServerContext* context, 
    const EmptyMessage* request,
    EmptyMessage* response
  ) override {
    std::cout << "[ACK] Received the request to run the setup:" << std::endl;

    libzeth::CircuitWrapper<JSIns, JSOut> prover;
    libsnark::r1cs_ppzksnark_keypair<ppT> keypair = prover.generate_trusted_setup();

    return Status::OK;
  }

  libzeth::ZethNote ParseZethNote(const proverpkg::ZethNote& note) {
    bits256 noteAPK = libzeth::hexadecimal_digest_to_bits256(note.apk());
    bits64 noteValue = libzeth::hexadecimal_value_to_bits64(note.value());
    bits256 noteRho = libzeth::hexadecimal_digest_to_bits256(note.rho());
    bits384 noteRTrapR = libzeth::get_bits384_from_vector(libzeth::hexadecimal_str_to_binary_vector(note.trapr()));

    return libzeth::ZethNote(
      noteAPK,
      noteValue,
      noteRho,
      noteRTrapR
    );
  }

  libsnark::merkle_authentication_node ParseMerkleNode(std::string mk_node) {
    return libff::bit_vector(libzeth::hexadecimal_digest_to_binary_vector(mk_node));
  }

  libzeth::JSInput ParseJSInput(const proverpkg::JSInput& input) {
        if (ZETH_MERKLE_TREE_DEPTH != input.merklenode_size()) {
          throw std::invalid_argument("Invalid merkle path length");
        }

        libzeth::ZethNote inputNote = ParseZethNote(input.note());
        size_t inputAddress = input.address();
        bitsAddr inputAddressBits = libzeth::get_bitsAddr_from_vector(libzeth::address_bits_from_address(inputAddress, ZETH_MERKLE_TREE_DEPTH));
        bits256 inputSpendingASK = libzeth::hexadecimal_digest_to_bits256(input.spendingask());
        bits256 inputNullifier = libzeth::hexadecimal_digest_to_bits256(input.nullifier());

        std::vector<libsnark::merkle_authentication_node> inputMerklePath;
        for(int i = 0; i < ZETH_MERKLE_TREE_DEPTH; i++) {
          libsnark::merkle_authentication_node mk_node = ParseMerkleNode(input.merklenode(i));
          inputMerklePath.push_back(mk_node);
        }

        return libzeth::JSInput(
          inputMerklePath,
          inputAddress,
          inputAddressBits,
          inputNote,
          inputSpendingASK,
          inputNullifier
        );
  }
  
  Status Prove(
    ServerContext* context,
    const ProofInputs* proofInputs,
    ExtendedProof* proof
  ) override {
    std::cout << "[ACK] Received the request to generate a proof:" << std::endl;

    // Parse received message to feed to the prover
    try {
      libzeth::bits256 root_bits = libzeth::hexadecimal_digest_to_bits256(proofInputs->root());
      libzeth::bits64 vpub_in = libzeth::hexadecimal_value_to_bits64(proofInputs->inpubvalue());
      libzeth::bits64 vpub_out = libzeth::hexadecimal_value_to_bits64(proofInputs->outpubvalue());

      if (JSIns != proofInputs->jsinputs_size()) {
        throw std::invalid_argument("Invalid number of JS inputs");
      }
      if (JSOut != proofInputs->jsoutputs_size()) {
        throw std::invalid_argument("Invalid number of JS outputs");
      }

      std::cout << "Process every inputs of the JoinSplit" << std::endl;
      std::array<libzeth::JSInput, JSIns> jsInputs;
      for(int i = 0; i < JSIns; i++) {
        proverpkg::JSInput receivedInput = proofInputs->jsinputs(i);
        libzeth::JSInput parsedInput = ParseJSInput(receivedInput);
        jsInputs[i] = parsedInput;
      }

      std::cout << "Process every outputs of the JoinSplit" << std::endl;
      std::array<libzeth::ZethNote, JSOut> jsOutputs;
      for(int i = 0; i < JSOut; i++) {
        proverpkg::ZethNote receivedOutput = proofInputs->jsoutputs(i);
        libzeth::ZethNote parsedOutput = ParseZethNote(receivedOutput);
        jsOutputs[i] = parsedOutput;
      }

      std::cout << "SUCCESS" << std::endl;
    } catch (const std::exception& e) {
      std::cout << "[ERROR] " << e.what() << std::endl;
      return ::grpc::Status(::grpc::StatusCode::INVALID_ARGUMENT, grpc::string(e.what()));
    } catch (...) {
      return ::grpc::Status(::grpc::StatusCode::UNKNOWN, "");
    }
    
    // myCustomProveFunction()

    return Status::OK;
  }
};

void ServerStartMessage() {
  std::string copyright = "Copyright (c) 2015-2019 Clearmatics Technologies Ltd";
  std::string license = "SPDX-License-Identifier: LGPL-3.0+";
  std::string project = "R&D Department: PoC for Zerocash on Ethereum/Autonity";
  std::string version = "Version [TBD Use the zethConfig]";
  std::string warning = "**WARNING:** This code is a research-quality proof of concept, DO NOT USE in production!";

  std::cout << "\n=====================================================" << std::endl;
  std::cout << copyright << std::endl;
  std::cout << license << std::endl;
  std::cout << project << std::endl;
  std::cout << version << std::endl;
  std::cout << warning << std::endl;
  std::cout << "=====================================================\n" << std::endl;
}

void RunServer() {
  // Listen for incoming connections on 0.0.0.0:50051
  std::string server_address("0.0.0.0:50051");
  ProverImpl service;

  ServerBuilder builder;

  // Listen on the given address without any authentication mechanism.
  builder.AddListeningPort(server_address, grpc::InsecureServerCredentials());

  // Register "service" as the instance through which we'll communicate with
  // clients. In this case it corresponds to an *synchronous* service.
  builder.RegisterService(&service);

  // Finally assemble the server.
  std::unique_ptr<Server> server(builder.BuildAndStart());
  std::cout << "Server listening on " << server_address << std::endl;

  // Wait for the server to shutdown. Note that some other thread must be
  // responsible for shutting down the server for this call to ever return.
  ServerStartMessage();
  server->Wait();
}

int main(int argc, char** argv) {
  // We inititalize the curve parameters here
  ppT::init_public_params();

  RunServer();
  return 0;
}
