#ifndef __ZETH_CONSTANTS__
#define __ZETH_CONSTANTS__

#define ZETH_NUM_JS_INPUTS 2
#define ZETH_NUM_JS_OUTPUTS 2

#define ZETH_MERKLE_TREE_DEPTH 4
#define ZETH_MERKLE_TREE_DEPTH_TEST 4

#endif // __ZETH_CONSTANTS__
