#!/usr/bin/env python3

from coordinator.crypto import \
    generate_signing_key, get_verification_key, export_signing_key, \
    export_verification_key
from click import command, argument


@command()
@argument("key-file")
def generate_key(key_file: str) -> None:
    """
    Generate new private key to key-file.  Public key is written to stdout.
    """
    signing_key = generate_signing_key()
    verification_key = get_verification_key(signing_key)

    with open(key_file, "wb") as out_f:
        out_f.write(export_signing_key(signing_key))

    print(export_verification_key(verification_key))


if __name__ == "__main__":
    generate_key()
