#!/usr/bin/env python3

"""
Script to launch a null server.  Press CTRL-C to stop
"""

from click import command, option


@command()
@option("--path", default=".", help="Server working path")
def null_server(path: str) -> None:
    from coordinator.null_contribution_handler import NullContributionHandler
    from coordinator.server import Server
    import time

    handler = NullContributionHandler()
    try:
        server = Server(handler, path)
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        server.stop()


if __name__ == "__main__":
    null_server()
