#!/usr/bin/env python3

"""
Script to launch a phase1 coordinator server.
"""

from click import command, option
from typing import Optional


@command()
@option("--pot-path", default=None, help="Path to poweroftau repository")
def phase1_server(bin_path: Optional[str]) -> None:
    from coordinator.phase1_contribution_handler import \
        Phase1ContributionHandler
    from coordinator.server import Server
    import time

    try:
        server = Server(Phase1ContributionHandler(), ".")
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        server.stop()


if __name__ == "__main__":
    phase1_server()
