#!/usr/bin/env python3

from coordinator.contribute import contribute
from coordinator.powersoftau_command import \
    PowersOfTauCommand, CHALLENGE_FILE, RESPONSE_FILE
from typing import Optional
from click import command, option, argument, ClickException
from os.path import exists

# CHALLENGE_FILE = "challenge.bin"
# RESPONSE_FILE = "response.bin"
RESPONSE_DIGEST_FILE = "response.bin.digest"


@command()
@argument("base-url")
@argument("key-file")
@option("--pot-path", default=None, help="path to powersoftau repo")
@option("--response-digest", default=RESPONSE_DIGEST_FILE)
@option("--num-powers", "-n", default=None, type=int, help="number of powers")
@option("--skip-user-input", is_flag=True, default=False)
@option("--server-certificate", default=None, help="server certificate")
def phase1_contribute(
        base_url: str,
        key_file: str,
        pot_path: Optional[str],
        response_digest: str,
        num_powers: Optional[int],
        skip_user_input: bool,
        server_certificate: Optional[str]) -> None:
    """
    Download a challenge, then compute, sign and upload an MPC contribution
    """

    # Compute contribution
    def _contribute() -> str:
        pot = PowersOfTauCommand(pot_path, num_powers)
        contribution_success = pot.contribute(response_digest, skip_user_input)
        if not contribution_success:
            raise ClickException("failed to generate response")
        if not exists(RESPONSE_FILE):
            raise ClickException("response file not created")
        return RESPONSE_FILE

    contribute(
        base_url, key_file, CHALLENGE_FILE, _contribute, server_certificate)


if __name__ == "__main__":
    phase1_contribute()
