#!/usr/bin/env python3

# Copyright (c) 2015-2022 Clearmatics Technologies Ltd
#
# SPDX-License-Identifier: LGPL-3.0+

from commands.public_key_operations import public_key_information
from coordinator.crypto import import_signing_key
from click import command, argument, option
from typing import Optional


@command()
@argument("key-file")
@option("--public-key", "public_key_file", default=None, help="Public key file")
@option("--evidence", "evidence_file", default=None, help="Evidence file")
def public_key_cmd(
        key_file: str,
        public_key_file: Optional[str],
        evidence_file: Optional[str]) -> None:
    """
    Load signing key and print public information to stdout.
    """

    with open(key_file, "rb") as key_f:
        key = import_signing_key(key_f.read())
    public_key_information(key, public_key_file, evidence_file)


if __name__ == "__main__":
    public_key_cmd()
