#!/usr/bin/env python3

# Copyright (c) 2015-2022 Clearmatics Technologies Ltd
#
# SPDX-License-Identifier: LGPL-3.0+

from coordinator.client import Client
import coordinator.contribute as contribute
from click import command, argument, option
from typing import Optional


@command()
@argument("base-url")
@argument("key-file")
@argument("response-file")
@option("--server-certificate", default=None, help="Server certificate")
@option("--insecure", is_flag=True, help="Allow missing certificate chain")
def upload_contribution(
        base_url: str,
        key_file: str,
        response_file: str,
        server_certificate: Optional[str],
        insecure: bool) -> None:
    """
    Manually upload a response to the MPC challenge (usually performed as part
    of a contribute command).
    """
    client = Client(base_url, server_certificate, insecure)
    contribute.upload_response(client, response_file, key_file)


if __name__ == "__main__":
    upload_contribution()
