name: "code-scanning"

on:
  push:
  pull_request:
  # Schedule code scanning
  #schedule:
  #  - cron: '0 1 * * 0'

env:
  MACOS_BREW_PACKAGES: "pkg-config libomp"

jobs:

  codeql-cpp-build-macos:
    # For now, run the cpp analysis on macOS only for ease of grpc installation
    runs-on: macos-latest
    steps:
      - name: Checkout repository and install submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: brew install ${MACOS_BREW_PACKAGES}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
        # Autobuild for compiled languages.
        #- name: Autobuild
        #  uses: github/codeql-action/autobuild@v1
      - name: Custom build
        run: CI_CONFIG=Release scripts/ci build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  codeql-py-build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Custom dependencies installation
        run: |
          cd client
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          make setup
          echo "::set-env name=CODEQL_PYTHON::$(which python)"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
          # Override default behavior for custom python deps installation
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

