name: zeth-ci-code-scanning

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master
  # TODO: Consider scheduling code scanning
  #schedule:
  #  - cron: '0 1 * * 0'

env:
  MACOS_BREW_PACKAGES: "pkg-config libomp"

jobs:

  codeql-cpp-build-macos:
    # For now, run the cpp analysis on macOS only for ease of grpc installation
    runs-on: macos-latest
    steps:
      - name: Checkout repository and install submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Dependencies
        run: brew install ${MACOS_BREW_PACKAGES}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp
      - name: Custom build
        run: CI_CONFIG=Release scripts/ci build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  codeql-py-build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: codeql-py-pip-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
      - name: Custom dependencies installation
        run: |
          cd client
          python3 -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip --progress-bar off
          pip install --upgrade setuptools wheel
          make setup
          echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: python
          # Override default behavior for custom python deps installation
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
