name: "Develop. Docker build apps"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

env:
  REPO_OWNER: "clearmatics"

jobs:

  docker-build:
    name: "Docker build"
    runs-on: ubuntu-20.04
    timeout-minutes: 360

    strategy:
      fail-fast: false
      matrix:
        app: ['mpc', 'client', 'prover']
      max-parallel: 3

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Get vars from git"
        id: git_vars
        run: echo ::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)

      - name: "Login to DockerHub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Docker build"
        run: docker build -f ./Dockerfile-${{ matrix.app }} -t $REPO_OWNER/zeth-${{ matrix.app }}:git-${{ steps.git_vars.outputs.COMMIT_HASH }} .

      - name: "Docker push"
        run: docker push $REPO_OWNER/zeth-${{ matrix.app }}:git-${{ steps.git_vars.outputs.COMMIT_HASH }}

      - name: "Docker Info"
        run: |
          docker inspect $REPO_OWNER/zeth-${{ matrix.app }}:git-${{ steps.git_vars.outputs.COMMIT_HASH }}
          docker history $REPO_OWNER/zeth-${{ matrix.app }}:git-${{ steps.git_vars.outputs.COMMIT_HASH }} --no-trunc
          docker version
          docker info
          uname -a
