name: zeth-ci-dev-docs

on:
  push:
    branches: [ extend-doxy-config ]
    #branches: [ develop ]

jobs:
  build-grpc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/grpc
    - name: Build grpc
      run: if ! [ -d depends/grpc ] ; then scripts/install_grpc /usr v1.31.x ; fi

  build-documentation:
    runs-on: ubuntu-20.04
    needs: build-grpc
    steps:
    - name: Checkout repository and install submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache grpc
      uses: actions/cache@v2
      with:
        key: grpc-1.31.x-${{ runner.os }}
        path: depends/grpc
    - name: Install dependencies
      run: |
        sudo apt update -y
        source scripts/build_utils.sh
        init_platform
        cpp_build_setup
        INSTALL_ONLY=1 scripts/install_grpc /usr v1.31.x
        sudo apt install -y doxygen graphviz
    - name: Generatate documentation
      run: |
        mkdir -p build
        pushd build
        cmake -DGEN_DOC=ON ..
        make build_docs
        popd
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/doc_doxygen/html/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: doxy-gh-pages
