# Build actions for every push on macOS
name: zeth-ci-push-build-macos

on:
  push:

env:
  MACOS_BREW_PACKAGES: "pkg-config libomp"

jobs:

  build-macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Install Dependencies
      run: brew install ${MACOS_BREW_PACKAGES}
    - name: Execute
      run: CI_CONFIG=${{ matrix.config }} scripts/ci build

