# Build actions for every push on macOS
name: zeth-ci-push-build-macos

on:
  push:

env:
  MACOS_BREW_PACKAGES: "autoconf automake boost cmake gmp openssl pkg-config libomp libtool"
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:

  # Extract the commits of submodules for use by cache steps
  submodules:
    runs-on: ubuntu-20.04
    outputs:
      commits: ${{ steps.get-commits.outputs.commits }}
    steps:
    - uses: actions/checkout@v2
    - name: Get Submodule Commits
      id: get-commits
      run: |
        git submodule sync
        echo "::set-output name=commits::"`git submodule status depends/libsodium | grep -oe '[0-9a-fA-F]\+' | head -c 8`-`git submodule status depends/libsnark | grep -oe '[0-9a-fA-F]\+' | head -c 8`

  # Main build
  build-macos:
    runs-on: macos-11
    needs: submodules
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache ccache
      uses: actions/cache@v2
      with:
        key: submodules-${{ needs.submodules.outputs.commits }}-${{ runner.os }}-${{ matrix.config }}
        path: ~/Library/Caches/ccache
    - name: Cache pip (for mpc tests)
      uses: actions/cache@v2
      with:
        path: ~/Library/Caches/pip
        key: build-macos-pip-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
    - name: Install Dependencies
      run: |
        brew link llvm@14
        which clang
        clang --version
        brew install ${MACOS_BREW_PACKAGES}
    - name: Execute
      run: CI_MPC_TESTS=1 CI_CONFIG=${{ matrix.config }} scripts/ci build
