# Check actions (linters, analysis tools etc.)
name: zeth-ci-onpush-checks

on:
  push:

jobs:

  check-contracts:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.solcx
        key: check-contracts-pip-solcx-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
    - name: Check Contracts
      run: scripts/ci check_contracts

  check-client:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: check-client-pip-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
    - name: Check Client
      run: scripts/ci check_client

  check-cpp-linux:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Execute
      run: CI_CHECK_FORMAT=1 CI_USE_DOCKER=1 scripts/ci check_cpp
