# Build actions for every push on macOS
name: zeth-ci-push-build-macos

on:
  push:

env:
  MACOS_BREW_PACKAGES: "pkg-config libomp ccache"

jobs:

  # Main build
  build-macos:
    runs-on: macos-10.15
    strategy:
      matrix:
        config: [ Debug, Release ]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Ccache cache
      id: ccache
      uses: ./.github/workflows//ccache
      with:
        cache-id: build-macos
    - name: Display ccache cache key
      run: |
        echo "Cache key: "${{ steps.ccache.outputs.cache-key }}
    # - name: Cache pip (for mpc tests)
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/Library/Caches/pip
    #     key: build-macos-pip-${{ hashFiles('**/setup.py') }}-${{ runner.os }}
    # - name: Install Dependencies
    #   run: brew install ${MACOS_BREW_PACKAGES}
    # - name: Execute
    #   run: CI_MPC_TESTS=1 CI_CONFIG=${{ matrix.config }} scripts/ci build
