name: release-docker-build-zeth-base

on:
  push:
    tags:
      - docker-base-v[0-9]+.[0-9]+.[0-9]+ # Triggered by git tags like: docker-base-v0.2.12

jobs:

  docker-build:
    name: "Docker build"
    runs-on: ubuntu-20.04
    timeout-minutes: 360

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Create swap from file"
        run: |
            sudo fallocate -l 19G /swapfile2
            sudo chmod 600 /swapfile2
            sudo mkswap /swapfile2
            sudo swapon /swapfile2

      - name: "Show build host parameters"
        run: |
          free -h
          df -h
          nproc

      - name: "Get vars from git"
        id: git_vars
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/docker-base-v/}

      - name: "Configure Docker"
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: "Docker build"
        run: docker build -f ./Dockerfile-base -t ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-base .

      - name: "Docker push"
        run: |
          docker push ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-base
          docker tag ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-base ghcr.io/$GITHUB_REPOSITORY:latest-base
          docker push ghcr.io/$GITHUB_REPOSITORY:latest-base

      - name: "Docker Info"
        run: |
          docker inspect ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-base
          docker history ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-base --no-trunc
          docker version
          docker info
          uname -a
