name: release-docker-build-zeth-apps

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+ # Triggered by git tags like: v0.2.12

jobs:

  docker-build:
    name: Docker build
    runs-on: ubuntu-20.04
    timeout-minutes: 180

    strategy:
      fail-fast: true
      matrix:
        # Disable mpc for now
        # app: ['mpc', 'client', 'prover']
        app: ['client', 'prover']
      max-parallel: 3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get vars from git
        id: git_vars
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
          echo ::set-output name=COMMIT_HASH::$(git rev-parse --short HEAD)

      - name: Configure Docker
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Set up Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build and push image git-SHA
        run: |
          docker buildx build \
            --tag ghcr.io/$GITHUB_REPOSITORY:git-${{ steps.git_vars.outputs.COMMIT_HASH }}-${{ matrix.app }} \
            --cache-from=type=registry,ref=ghcr.io/$GITHUB_REPOSITORY:cache-${{ matrix.app }} \
            --cache-to=type=registry,ref=ghcr.io/$GITHUB_REPOSITORY:cache-${{ matrix.app }} \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --file ./Dockerfile-${{ matrix.app }} ./

      - name: Tag and push latest image to registry
        run: |
          docker pull ghcr.io/$GITHUB_REPOSITORY:git-${{ steps.git_vars.outputs.COMMIT_HASH }}-${{ matrix.app }}
          docker tag ghcr.io/$GITHUB_REPOSITORY:git-${{ steps.git_vars.outputs.COMMIT_HASH }}-${{ matrix.app }} ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-${{ matrix.app }}
          docker tag ghcr.io/$GITHUB_REPOSITORY:git-${{ steps.git_vars.outputs.COMMIT_HASH }}-${{ matrix.app }} ghcr.io/$GITHUB_REPOSITORY:latest-${{ matrix.app }}
          docker push ghcr.io/$GITHUB_REPOSITORY:${{ steps.git_vars.outputs.VERSION }}-${{ matrix.app }}
          docker push ghcr.io/$GITHUB_REPOSITORY:latest-${{ matrix.app }}
